export {
  addKeyframe,
  createAnimationState,
  deleteTime,
  findKeyframeAt,
  getAnimationSessionVersion,
  getAnimationVersion,
  getDuration,
  getKeyframe,
  getKeyframeCount,
  getKeyframesForNode,
  getKeyframesForTrack,
  getPlayheadTime,
  insertTime,
  isLooping,
  isPlaying,
  removeKeyframe,
  setDuration,
  setLooping,
  setPlaying,
  setPlayheadTime,
  updateKeyframe,
  validateAnimationState,
} from './animationState';

export type { AnimationDiagnostic, AnimationState, EasingFunction, Keyframe } from './animationState';
