export {
  addComponentInstance,
  clearInstanceOverrides,
  createComponentState,
  detachComponentInstance,
  getBrokenComponentInstances,
  getComponentDefinition,
  getComponentDefinitionCount,
  getComponentDefinitions,
  getComponentInstance,
  getComponentVersion,
  getInstancesOfDefinition,
  registerComponent,
  relinkComponentDefinition,
  removeComponentInstance,
  setInstanceOverrides,
  setInstanceVariant,
  swapComponentInstance,
  unregisterComponent,
  updateComponentDefinition,
  validateComponentState,
} from './componentState';
export { createComponentCommand } from './componentCommand';

export type {
  ComponentDefinition,
  ComponentDiagnostic,
  ComponentInstance,
  ComponentOverride,
  ComponentOverrideKind,
  ComponentPropagationReport,
  ComponentState,
  ComponentVariantDimension,
  DetachedComponentInstance,
} from './componentState';
