export {
  addComponentInstance,
  clearInstanceOverrides,
  createComponentState,
  detachComponentInstance,
  getBrokenComponentInstances,
  getComponentDefinition,
  getComponentDefinitionCount,
  getComponentDefinitions,
  getComponentInstance,
  getComponentVersion,
  getInstancesOfDefinition,
  registerComponent,
  relinkComponentDefinition,
  removeComponentInstance,
  setInstanceOverrides,
  swapComponentInstance,
  unregisterComponent,
  validateComponentState,
} from './componentState';

export type {
  ComponentDefinition,
  ComponentDiagnostic,
  ComponentInstance,
  ComponentOverride,
  ComponentOverrideKind,
  ComponentState,
  DetachedComponentInstance,
} from './componentState';
